# Schema for the configuration files of the Static Generator module.

static_generator.settings:
  type: config_object
  label: 'Static generator settings'
  mapping:
    generator_directory:
      type: string
      label: 'Generator directory'
    paths_generate:
      type: string
      label: 'Paths to Generate'
    paths_do_not_generate:
      type: string
      label: 'Paths to not generate.'
    blocks_esi:
      type: string
      label: 'Block ids to generate.'
    blocks_no_esi:
      type: string
      label: 'Block ids to not generate.'
    blocks_frequent:
      type: string
      label: 'Block ids to not generate.'
    drupal:
      type: string
      label: 'Drupal directories and files.'
    non_drupal:
      type: string
      label: 'Non Drupal directories and files.'
    gen_node:
      type: string
      label: 'Node bundles to generate.'
    rsync_public:
      type: string
      label: 'rSync for generating Drupal public files.'
    rsync_public_exlude:
      type: string
      label: 'Public files to exclude.'
    rsync_code:
      type: string
      label: 'rSync for generating Drupal code files.'
    verbose_logging:
      type: boolean
      label: 'Turn on verbose logging.'
    generate_index:
      type: boolean
      label: 'Generate index.html.'
    static_url:
      type: string
      label: 'Turn on verbose logging.'


