# Schema for the configuration files of the Static Generator module.

static_generator.settings:
  type: config_object
  label: 'Static generator settings'
  mapping:
    generator_directory:
      type: string
      label: 'Generator directory'
    paths_generate:
      type: string
      label: 'Paths to Generate'
    paths_do_not_generate:
      type: string
      label: 'Paths to not generate.'
    blocks_esi:
      type: string
      label: 'Block ids to generate.'
    blocks_no_esi:
      type: string
      label: 'Block ids to not generate.'
    gen_node:
      type: string
      label: 'Node bundles to generate.'
    rsync_public:
      type: string
      label: 'rSync for generating Drupal public files..'
    verbose_logging:
      type: boolean
      label: 'Turn on verbose logging.'

