# Schema for the configuration files of the Static Generator module.

static_generator.settings:
  type: config_object
  label: 'Static generator settings'
  mapping:
    generator_directory:
      type: string
      label: 'Generator directory'
    paths_generate:
      type: string
      label: 'Paths to Generate'
    paths_do_not_generate:
      type: string
      label: 'Paths to not generate.'
    gen_block:
      type: string
      label: 'Block bundles to generate.'
    gen_node:
      type: string
      label: 'Node bundles to generate.'